# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170728_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
