# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170804_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('A', 'Apparel'), ('D', 'DVDs'), ('C', 'CDs'), ('O', 'Others')], max_length=1),
        ),
    ]
