# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170811_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='No info', null=True),
        ),
    ]
