# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('caption', models.CharField(max_length=200)),
                ('url', models.TextField(default='http://via.placeholder.com/200x200')),
            ],
        ),
    ]
